name: Neptune Tests

on: [push]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: short

jobs:
  test_a:
    runs-on: self-hosted
    name: Neptune test A
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: nvcc --version
      - run: clinfo
      - run: nvidia-smi
      - run: echo "Starting Neptune test A"
      - run: cargo test
  #test_b:
  #  runs-on: self-hosted
  #  name: Neptune test B
  #  steps:
  #    - uses: actions/checkout@v3
  #    - uses: Swatinem/rust-cache@v2
  #    - run: echo "Starting Neptune test B"
  #    - run: cargo test
